services:
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    environment:
      - PORT=${PORT}

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_API_AUTHORIZATION_KEY=${VITE_API_AUTHORIZATION_KEY}
    ports:
      - "8080:80"
    depends_on:
      - api